# Site settings
title: Adam Altmejd
tagline: "Adam Altmejd's personal webpage"
author:
    name: Adam Altmejd
    email: adam@altmejd.se
    github: adamaltmejd
    twitter: adamaltmejd
    facebook: adam.altmejd
    linkedin: adamaltmejd
description: "Personal webpage of Adam Altmejd, PhD Student in Economics"
baseurl: ""
url: "https://adamaltmejd.se"

# Timezone
timezone: Europe/Stockholm

markdown: kramdown
kramdown:
    input: GFM

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "projects/page:num"

highlighter: rouge

# SASS settings
sass:
    sass_dir: _sass
    style: :compressed

# Disable custom plugins, and ignore symbolic links. (github: true)
safe: true

# Publish posts with a future date
future: false

# Site source (github: .)
source: .

# Include .well-known (for keybase, robots.txt, etc)
include: [".well-known"]

# Where to put the compiled site
destination: ./_site

# Exclude these files from compilation (dotfiles by default)
exclude: [
    "Gemfile",
    "Gemfile.lock",
    "CNAME",
    "README.md",
    "bower_components",
    "package.json",
    "bower.json",
    "Gruntfile.js",
    "node_modules",
]

# Produce an index for related posts (github: false)
lsi: false

# Permalink style
permalink: /:categories/:title/
