# Site settings
title: Adam Altmejd
tagline: "Adam Altmejd's personal webpage"
author:
  name: Adam Altmejd
  givenName: Adam
  familyName: Altmejd
  email: adam@altmejd.se
  phone: +46 734 20 01 20
  github: adamaltmejd
  twitter: adamaltmejd
  facebook: adam.altmejd
  linkedin: adamaltmejd
  orcid: 0000-0002-4248-0677
  gscholarid: xyMRB8cAAAAJ
description: "Personal webpage of Adam Altmejd, PhD Student in Economics"
baseurl: ""
url: "https://adamaltmejd.se"
repository: adamaltmejd/adamaltmejd.github.io

# Timezone
timezone: Europe/Stockholm

# Publish posts with a future date
future: false

# Pagination
paginate: 10
paginate_path: "projects/page:num"

# https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
  - jekyll-coffeescript # github forced
  - jekyll-gist # github forced
  - jekyll-github-metadata # github forced
  - jekyll-paginate # github forced
  - jekyll-relative-links # github forced
  - jekyll-optional-front-matter # github forced
  - jekyll-readme-index # github forced
  - jekyll-default-layout # github forced
  - jekyll-titles-from-headings # github forced
  #- jemoji # github optional
  #- jekyll-seo-tag # github optional
  #- jekyll-sitemap # github optional
  #- jekyll-redirect-from # github optional
  #- jekyll-feed # github optional
  #- jekyll-include-cache # github optional
  #- jekyll-avatar # github optional
  #- jekyll-mentions # github optional

# SASS settings
# sass:
#   sass_dir: _sass
#   style: :expanded
#   sourcemap: true

# Include .well-known (for keybase, robots.txt, etc)
include: [".well-known"]

# Exclude these files from compilation (dotfiles by default)
exclude: [
  "node_modules",
  "Gemfile",
  "Gemfile.lock",
  "CNAME",
  "README.md",
  ".editorconfig",
  "package.json",
  "package-lock.json",
  "yarn.lock",
  "Gruntfile.js",
  "gulpfile.babel.js",
  "adamaltmejd.code-workspace"
]

# Permalink style
permalink: /:categories/:title/

# Github pages defaults (forced)
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
