# Site settings
title: Adam Altmejd
tagline: "Adam Altmejd's personal webpage"
author:
  name: Adam Altmejd
  email: adam@altmejd.se
  github: adamaltmejd
  twitter: adamaltmejd
  facebook: adam.altmejd
  linkedin: adamaltmejd
description: "Personal webpage of Adam Altmejd, PhD Student in Economics"
baseurl: ""
url: "https://adamaltmejd.se"
repository: adamaltmejd/adamaltmejd.github.io

# Timezone
timezone: Europe/Stockholm

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax # github: mathjax

gist:
  noscript: false # github: false

gems:
  - jekyll-coffeescript # github default
  - jekyll-paginate # github default
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap

# because we have safe: true to mimic github pages we need to add
whitelist:
  - jekyll-coffeescript # github default
  - jekyll-paginate # github default
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: "projects/page:num"

# Syntax highlighting (github: rouge)
highlighter: rouge

# SASS settings
sass:
  sass_dir: _sass
  style: :expanded

# Disable custom plugins, and ignore symbolic links. (github: true)
safe: true

# Publish posts with a future date
future: false

# Site source (github: .)
source: .

# Include .well-known (for keybase, robots.txt, etc)
include: [".well-known"]

# Where to put the compiled site
destination: ./_site

# Incremental builds (github: false)
incremental: false

# Exclude these files from compilation (dotfiles by default)
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "CNAME",
  "README.md",
  "bower_components",
  "package.json",
  "bower.json",
  "Gruntfile.js",
  "node_modules"
]

# Produce an index for related posts (github: false)
lsi: false

# Permalink style
permalink: /:categories/:title/
