name = "Researcher"
license = "MIT"
licenselink = "https://github.com/adamaltmejd/adamaltmejd.github.io/blob/master/LICENSE"
description = "A clean, minimal Hugo theme for academic personal websites"
min_version = "0.136.0"

[author]
  name = "Adam Altmejd"
  homepage = "https://adamaltmejd.se"
